# Generated by Django 6.0 on 2026-01-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('Clothing', 'Clothing'), ('Food', 'Food'), ('Accessories', 'Accessories'), ('Cosmetics', 'Cosmetics'), ('Technology', 'Technology')], max_length=50),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
    ]
