# Generated by Django 6.0 on 2026-01-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_shopprofile_category_shopprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('clothing', 'Clothing'), ('food', 'Food'), ('accessories', 'Accessories'), ('cosmetics', 'Cosmetics'), ('technology', 'Technology')], max_length=50),
        ),
    ]
