# Generated by Django 6.0 on 2026-01-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_shopprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('offline', 'Offline'), ('on_delivery', 'On Delivery')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='total_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
