# Generated by Django 6.0 on 2026-01-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_riderprofile_rating_riderprofile_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='total_deliveries',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
