# Generated by Django 6.0 on 2026-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_riderprofile_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='license_number',
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
